name: Gradle Build
on: [ push ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle Build
        run: ./gradlew build
      - name: Run the Gradle package task
        run: './gradlew installDist'
      - name: Archive jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/install/qbittorrent-exporter/
